config/routes.rb
Rails.application.routes.draw do
  root 'customers#index'
  resources :articles

  resources :customers do
    resources :loans
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :loans

  validates :name, presence: true
  validates :cpf, presence: true, length: { in: 11..11 }
  validates :age, presence: true
  validates :location, presence: true
  validates :income, presence: true
end

app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_url, status: :see_other
  end

  private
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      redirect_to @customer
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])

    if @customer.update(customer_params)
      redirect_to @customer
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    redirect_to root_url, status: :see_other
  end

  private
    def customer_params
      params.require(:customer).permit(:name, :cpf, :age, :location, :income)
    end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  def create
    @customer = Customer.find(params[:customer_id])
    @loan = @customer.loans.create(loan_params)
    redirect_to root_url
  end

  private
    def loan_params
      params.require(:loan).permit(:client, :loan_type, :taxes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

<%= link_to "Voltar", articles_path %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article %>
    </li>
  <% end %>
</ul>

<%= link_to "New Article", new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

<%= link_to "Voltar", articles_path %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

<%= link_to "Voltar", articles_path %>

app/views/customers/_form.html.erb
<%= form_with model: customer do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% customer.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :cpf %><br>
    <%= form.text_field :cpf, maxlength: 11 %>
    <% customer.errors.full_messages_for(:cpf).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :age %><br>
    <%= form.text_field :age, type: :number %>
    <% customer.errors.full_messages_for(:age).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :location %><br>
    <%= form.text_field :location %>
    <% customer.errors.full_messages_for(:location).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :income %><br>
    <%= form.text_field :income, type: :number %>
    <% customer.errors.full_messages_for(:income).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Edit Customer</h1>

<%= render "form", customer: @customer %>

<%= link_to "Voltar", customers_path %>

app/views/customers/index.html.erb
<h1>Customers</h1>

<ul>
  <% @customers.each do |customer| %>
    <li>
      <%= link_to customer.name, customer %>
    </li>
  <% end %>
</ul>

<%= link_to "New Customer", new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render "form", customer: @customer %>

<%= link_to "Voltar", customers_path %>

app/views/customers/show.html.erb
<h1><%= @customer.name %></h1>

<p><%= @customer.cpf %></p>
<p><%= @customer.age %></p>
<p><%= @customer.location %></p>
<p><%= @customer.income %></p>

<ul>
  <li><%= link_to "Edit", edit_customer_path(@customer) %></li>
  <li><%= link_to "Destroy", customer_path(@customer), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

<h2>Loans</h2>
<% @customer.loans.each do |loan| %>
  <p>
    <strong>Client:</strong>
    <%= loan.client %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= loan.loan_type %>
  </p>

  <p>
    <strong>Taxes:</strong>
    <%= loan.taxes %>
  </p>
<% end %>

<h2>Add a loan:</h2>
<%= form_with model: [ @customer, @customer.loans.build ] do |form| %>
  <p>
    <%= form.label :client %><br>
    <%= form.text_field :client %>
  </p>
  <p>
    <%= form.label :loan_type %><br>
    <%= form.text_field :loan_type %>
  </p>
  <p>
    <%= form.label :taxes %><br>
    <%= form.text_field :taxes, type: :number %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to "Voltar", customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Creditas Ruby Challenge" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>